jenkins:
  systemMessage: "This system is configured for BIG-IP AS3 buffering only"
  globalNodeProperties:
    - envVars:
        env:
        - key: BIGIP_MGMT_URI
          value: ${BIGIP_MGMT_URI}
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
      globalMatrix:
        permissions:
          - "Overall/Administer:admin"
          - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy          
unclassified:
  location:
    url: http://jenkinshost:8080/
credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope: GLOBAL
            id: "bigip-creds"
            username: "${BIGIP_ADMIN_ID}"
            password: "${BIGIP_ADMIN_PASSWORD}"
jobs:
  - file: /usr/local/as3buffer.groovy